package com.rvkb.gitfs

import junit.framework.TestCase

class GitFSTest extends TestCase {

  private GitFS getGfs() {
    GitFS gfs = new GitFSBuilder("/tmp/myrepo/.git").
        setCreateIfEmpty(true).
        build()
    assert gfs != null
    return gfs
  }

  void testRepoIsInitializedWhenEmpty() {
    String str = gfs.doInSession(new UserInfo("foo", "foo@bar.com")) { Session s ->
      s.readFile(new File('/tmp/myrepo/gitfs.txt')) { InputStream is ->
        new InputStreamReader(is).readLine()
      }
    }
    assert str == "File generated by GitFS."
  }

  void testWriteFile() {
    def ms = System.currentTimeMillis()
    String txt = "this is some text $ms"
    String msg = "commit message $ms"
    WriteResult wr = gfs.doInSession(new UserInfo("foo", "foo@bar.com")) { Session session ->
      ByteArrayInputStream bis = new ByteArrayInputStream(txt.getBytes())
      return session.writeToFile(bis, new File("/tmp/myrepo/test.txt"), msg)
    }
    assertNotNull wr
    assertEquals msg, wr.message
    assertEquals "foo", wr.userInfo.username
    assertEquals "foo@bar.com", wr.userInfo.email
    new File("/tmp/myrepo/test.txt").withReader { r ->
      assertEquals txt, r.readLine()
    }
  }

  void testGetRevisions() {
    def ms = System.currentTimeMillis()
    String fileName = "/tmp/myrepo/textRevs${ms}.txt"
    for (it in 1..10) {
      String txt = "content$it"
      gfs.doInSession(new UserInfo("foo", "foo@bar.com")) { Session session ->
        ByteArrayInputStream bis = new ByteArrayInputStream(txt.getBytes())
        return session.writeToFile(bis, new File(fileName), "commit num $it")
      }
    }
    Iterable<Revision> revisions = gfs.doInSession(new UserInfo("foo", "foo@bar.com")) { Session s ->
      return s.getRevisions(new File(fileName), 100)
    }
    int count = 0
    revisions.each {
      println it
      count++
    }
    assertEquals 10, count
  }

}
